version: '3.3'

services: 
  db: #Container de MySQL
    image: mysql:5.7 #FROM mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always      
    environment:
      - ./config/db.env

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    ports: 
      - "8000:80"
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: cristiano
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
volumes: 
  db_data: {}